---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Census based cluster-sample in India

Anurag Ajay, CIMMYT


## Introduction

This is what will be done here
Hello

## Get data


```{r sampindia01}
library(readxl)
x <- read_excel("PCA1001_2011_MDDS.xlsx")[, 1:10]
head(x)
dim(x)
table(x$Level)
district <- unique(x[x$Level == "DISTRICT", "Name"])
district
```

## Population weighted sample of villages

```{r sampindia10}
villages <- x[x$Level == "VILLAGE" & x$TRU == "Rural", ]
dim(x)
samplesize <- 40

i <- sample(nrow(villages), samplesize, prob=villages$No_HH)
sel_villages <- villages[i, c(1:4, 7:10)]
```

Put the sub-district names back in

```{r sampindia20}
subdist <- unique(x[x$Level == "SUB-DISTRICT", c("Subdistt", "Name")])
subdist
colnames(subdist)[2] <- "Subdist"
sel_villages <- merge(sel_villages, subdist, by="Subdistt")
head(sel_villages)
```

Write to .csv (for use in excel)

```{r sampindia30}
sel_villages <- sel_villages[, c("State", "District", "Subdistt", "Town/Village", "Subdist", "Name", "No_HH")]

sel_villages <- sel_villages[order(sel_villages$Subdist, sel_villages$Name), ]

filename <- paste0(district, "_selected-villages.csv")
filename
write.csv(sel_villages, filename, row.names = FALSE)
head(read.csv(filename))
```


## List of persons


```
library(pdftools)
library(stringr)

filename <- "*.pdf$"
y <- pdf_text(filename)

# ************************************************** #

w <- str_extract_all(y,"ककपन ससखनप : \\d{1,4}")  
# # <- ककपन ससखनप  for UPo कगकह सपखयच : for Bihar
# ************************************************** #
u <- str_extract_all(w, "[0-9.]+")

x <- lapply(u, unique)


for (i in seq_along(x)) {
  filename = paste(z[[i]],".csv", sep = "")
  write.table(x[i],filename, row.names = FALSE, col.names = FALSE)
}

files <- list.files(pattern="*.csv")

allFiles <- llply(files, read.csv)

combined <- do.call("rbind", allFiles)

read_csv_filename <- function(files){
  ret <- read.csv(files)
  ret$Source <- files
  ret
}

allFiles <- ldply(files, read_csv_filename)

write.csv(allFiles, "finalHHNumber.csv")
```
