# Introduction

## Statistical vs mechanistic models

An *explanatory* model consists of a quantitative description of the mechanisms and processes that cause the behavior of a system (a limited part of reality that contains interrelated elements). 

To create an explanatory model, the system is analyzed and its processes and mechanisms are quantified separately. The model is built by integrating these descriptions for the entire system and crop growth is then a consequence of these underlying processes. If there are discrepancies between the model and the real system, the model may be adjusted by tuning variables to obtain better agreement.

The model is *explanatory* because the calculations involving rate variables are based on knowledge of the underlying physical, physiological and biochemical processes. 

Not all mechanistic models are explanatory --- they may just have a few simple rules. 

A *statistical* or *descriptive* model may reflect very little of the mechanisms that are causing the behavior. 


The models presented here are *deterministic*

