# Regional Agronomy

This e-book provides an interoduction to the new field of "Regional Agronomy". It introduces concepts, methods, tools, and workflows to study spatial and temporal variation in crop production. Understanding spatial variation across large areas is increasingly important to guide business, research, development, and policy. For example, it can support the development of location based farmer advisory services; it is essential to agricultural insurance programs; and it help identifying needs for and potential benefit from technology deverlopment and other interventions. 

The study of agriculture across large regions is a departure from the traditional "Field Agronomy" in which research focusses on variation between and within fields. This type of research is largely based on well-managed trials at experimental stations. This approach has been, and will remain of fundamental importance, but it can be challanging to directly interpret and use the results in larger areas. 

The fundamental challange that needs to be addressed is that agriculture is highly site-specific. Every field is a little, or a lot, different from another field in its abiotic conditions (temperature, rainfall, soil type), biotic conditions (such as the presence of beneficial or problematic organisms), and social and economic conditions (for example, land ownership, access to markets). Thus to understand crop production, and its problems and opportunities we need to account for spatial and temporal variability in the growing conditions on farmer fields, and the local social and economic conditions. 

This is not a new insight and there are many notable examples of geographical approaches to agronomy. Fore example, Karl H.W. Klages, a professor of agronomy, argued for the incorporation of "crop ecology" and "ecological crop geography" into the agronomy curriculum (Klages, 1928). In his classic book "Ecological Crop Geography", Klages (1949) described the geographical distribution of crops, and the social and ecological factors that explain these patterns. 

What has changed is the availability of data and computational tools. This includes spatial data from satellites, and farm household data from surveys. There is open [data data](https://gardian.bigdata.cgiar.org/) from experiments that can be aggregated. Computing tools like python and R allow for the easy integration of these data with more specialized algortihms, such as crop models, or machine learning.

So there is a lot of promise. This resource aims at helping you acquire some of the skills you need to do this type of work. 


